/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    './styles/**/*.{css,scss}',
  ],
  safelist: [
    // Ensure critical classes aren't purged in production
    'min-h-screen',
    'bg-gradient-to-br',
    'from-blue-50',
    'via-white',
    'to-indigo-50',
    'bg-white',
    'shadow-sm',
    'shadow-lg',
    'border-b',
    'border-gray-200',
    'border-gray-100',
    'rounded-xl',
    'rounded-2xl',
    'text-gray-900',
    'text-gray-600',
    'text-blue-600',
    'hover:text-blue-600',
    'transition-colors',
    'font-medium',
    'font-semibold',
    'font-bold',
    'border-blue-600',
    'pb-1',
    'animate-spin',
    'w-8',
    'h-8',
    'w-12',
    'h-12',
    'border-b-2',
    'mx-auto',
    'mb-2',
    'mb-3',
    'mb-6',
    'mb-8',
    'space-x-4',
    'space-x-8',
    'grid',
    'grid-cols-1',
    'md:grid-cols-4',
    'gap-6',
    'p-6',
    'p-8',
    'px-4',
    'py-6',
    'py-8',
    'max-w-7xl',
    'text-center',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-sm',
    'text-lg',
    'text-xs',
    'bg-green-50',
    'bg-green-100',
    'bg-green-500',
    'bg-blue-50',
    'bg-blue-100',
    'bg-blue-500',
    'bg-purple-50',
    'bg-purple-100',
    'bg-purple-500',
    'bg-orange-50',
    'bg-orange-100',
    'bg-orange-500',
    'bg-red-50',
    'bg-red-500',
    'text-green-800',
    'text-green-600',
    'text-blue-800',
    'text-blue-600',
    'text-purple-800',
    'text-purple-600',
    'text-orange-800',
    'text-orange-600',
    'text-red-800',
    'text-red-600',
    'text-white',
    'border-green-200',
    'border-blue-200',
    'border-purple-200',
    'border-orange-200',
    'border-red-200',
    'to-green-100',
    'to-blue-100',
    'to-purple-100',
    'to-orange-100',
    'from-green-50',
    'from-blue-50',
    'from-purple-50',
    'from-orange-50',
    'from-red-50',
    'rounded-full',
    'items-center',
    'justify-center',
    'flex',
    'hidden',
    'md:flex',
    'relative',
    'h-96',
    'lg:h-[600px]',
    'bg-gray-100',
    'mt-1',
    'mt-6',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          900: '#1e3a8a',
        },
        civic: {
          50: '#f0fdf4',
          100: '#dcfce7',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          900: '#14532d',
        },
        severity: {
          low: '#10b981',
          medium: '#f59e0b',
          high: '#ef4444',
          critical: '#dc2626',
        }
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        'pulse-slow': 'pulse 3s infinite',
        'bounce-subtle': 'bounce 2s infinite',
      }
    },
  },
  plugins: [],
}
