/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './styles/**/*.{css,scss}',
  ],
  mode: 'jit',
  // Only disable purging in production, allow it in development
  purge: process.env.NODE_ENV === 'production' ? false : undefined,
  safelist: [
    // Force include ALL classes to ensure styling works on Netlify
    {
      pattern: /^(bg|text|border|from|to|via)-(gray|blue|green|purple|orange|red|indigo)-(50|100|200|500|600|700|800|900)$/,
    },
    {
      pattern: /^(w|h)-(8|12|96)$/,
    },
    {
      pattern: /^(p|m|px|py|mb|mt|mx|space)-(1|2|3|4|6|8)$/,
    },
    {
      pattern: /^(rounded|shadow)-(sm|md|lg|xl|2xl|full)$/,
    },
    {
      pattern: /^(text|font)-(xs|sm|lg|xl|2xl|3xl|medium|semibold|bold)$/,
    },
    {
      pattern: /^(grid|flex|items|justify)-(center|between|start|end)$/,
    },
    {
      pattern: /^(transition|hover|duration)-(colors|all|300)$/,
    },
    // Core layout classes - FORCE INCLUDE EVERYTHING
    'min-h-screen',
    'max-w-7xl',
    'mx-auto',
    'bg-gradient-to-br',
    'from-purple-50',
    'via-blue-50',
    'to-indigo-100',
    'from-blue-50',
    'via-white', 
    'to-indigo-50',
    'bg-white',
    'shadow-sm',
    'shadow-lg',
    'border-b',
    'border-gray-200',
    'border-gray-100',
    'rounded-xl',
    'rounded-2xl',
    'rounded-lg',
    'rounded-full',
    'text-gray-900',
    'text-gray-600',
    'text-blue-600',
    'text-white',
    'hover:text-blue-600',
    'transition-colors',
    'font-medium',
    'font-semibold',
    'font-bold',
    'border-blue-600',
    'pb-1',
    'animate-spin',
    'w-8',
    'h-8',
    'w-12', 
    'h-12',
    'border-b-2',
    'mb-2',
    'mb-3',
    'mb-6',
    'mb-8',
    'space-x-4',
    'space-x-8',
    'grid',
    'grid-cols-1',
    'md:grid-cols-4',
    'gap-6',
    'p-6',
    'p-8',
    'px-4',
    'py-6',
    'py-8',
    'text-center',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-sm',
    'text-lg',
    'text-xs',
    'hidden',
    'md:flex',
    'flex',
    'items-center',
    'justify-center',
    'justify-between',
    'relative',
    'h-96',
    'lg:h-[600px]',
    'bg-gray-100',
    'mt-1',
    'mt-6',
    // Gradient backgrounds for cards
    'bg-gradient-to-br',
    'from-green-50',
    'to-green-100', 
    'from-blue-50',
    'to-blue-100',
    'from-purple-50',
    'to-purple-100',
    'from-orange-50',
    'to-orange-100',
    'from-red-50',
    'to-red-100',
    // Card colors
    'bg-green-50',
    'bg-green-100',
    'bg-green-500',
    'bg-blue-50',
    'bg-blue-100', 
    'bg-blue-500',
    'bg-purple-50',
    'bg-purple-100',
    'bg-purple-500',
    'bg-orange-50',
    'bg-orange-100',
    'bg-orange-500',
    'bg-red-50',
    'bg-red-500',
    // Text colors
    'text-green-800',
    'text-green-600',
    'text-blue-800',
    'text-blue-600',
    'text-purple-800',
    'text-purple-600',
    'text-orange-800',
    'text-orange-600',
    'text-red-800',
    'text-red-600',
    // Border colors
    'border-green-200',
    'border-blue-200',
    'border-purple-200',
    'border-orange-200',
    'border-red-200',
    // Brand gradient
    'bg-gradient-to-r',
    'from-blue-600',
    'to-indigo-600',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          900: '#1e3a8a',
        },
        civic: {
          50: '#f0fdf4',
          100: '#dcfce7',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          900: '#14532d',
        },
        severity: {
          low: '#10b981',
          medium: '#f59e0b',
          high: '#ef4444',
          critical: '#dc2626',
        }
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        'pulse-slow': 'pulse 3s infinite',
        'bounce-subtle': 'bounce 2s infinite',
      }
    },
  },
  plugins: [],
}
