[build]
  # Base directory for the build
  base = "frontend"
  
  # Build command
  command = "npm run build"
  
  # Directory to publish (relative to base directory)
  publish = "out"

[build.environment]
  NODE_VERSION = "18.20.8"

# Handle Next.js static export routing
[[redirects]]
  from = "/map"
  to = "/map.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Fallback for any other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
